# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..2).each do |i|
    config.vm.define "multifocal0#{i}" do |webserver|
      webserver.vm.box = "ubuntu/focal64"
      webserver.vm.hostname = "multifocal0#{i}"
    end
  end
end
