# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'focal64'
  config.vm.box_url = 'https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20210907.0.0/providers/virtualbox.box'
end
